/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false cloudflare/worker-configuration.d.ts` (hash: 802d08c862b5ab381669357949f19aeb)
interface __BaseEnv_Env {
	ARC_RPC_URL: string;
	ARC_PUBLIC_RPC_URL: string;
	ARC_USDC: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ARC_RPC_URL" | "ARC_PUBLIC_RPC_URL" | "ARC_USDC">> {}
}
